// Generated by CoffeeScript 1.3.3
(function() {
  var Hook;

  Hook = (function() {

    function Hook(options) {
      this.options = options != null ? options : {};
      if (this.options.localMode) {
        this.cssUrl = "http://localhost:8000/lib/hook.css";
      } else {
        this.cssUrl = "https://s3.amazonaws.com/assets.heroku.com/hook/hook.css";
      }
      console.log(this.cssUrl);
      this.app = this.options.app;
      this.head = document.querySelector("head");
      this.body = document.querySelector("body");
      this.attachStylesheet();
      this.attachDiv();
      window.addEventListener('click', this.hideMenu);
      document.querySelector("#hook a.toggler").addEventListener('click', this.toggleMenu);
    }

    Hook.prototype.attachStylesheet = function() {
      var link;
      link = document.createElement("link");
      link.type = "text/css";
      link.rel = "stylesheet";
      link.href = this.cssUrl;
      return this.head.appendChild(link);
    };

    Hook.prototype.attachDiv = function() {
      this.div = document.createElement("div");
      this.div.className = "hook";
      this.div.id = "hook";
      if (this.app != null) {
        this.div.innerHTML = "<a href=\"#\" class=\"toggler\">heroku</a>\n<ul>\n  <li class=\"big\"><a href=\"https://dashboard.heroku.com/apps/" + this.app + "\">" + this.app + "</a></li>\n  <li class=\"sub\"><a href=\"https://dashboard.heroku.com/apps/" + this.app + "/resources\">Resources</a></li>\n  <li class=\"sub\"><a href=\"https://dashboard.heroku.com/apps/" + this.app + "/activity\">Activity</a></li>\n  <li class=\"sub\"><a href=\"https://dashboard.heroku.com/apps/" + this.app + "/collaborators\">Collborators</a></li>\n  <li class=\"sub\"><a href=\"https://dashboard.heroku.com/apps/" + this.app + "/settings\">Settings</a></li>\n</ul>";
      } else {
        this.div.innerHTML = "<a href=\"#\" class=\"toggler\">heroku</a>\n<ul>\n  <li><a href=\"https://dashboard.heroku.com\">My Apps</a></li>\n  <li><a href=\"https://addons.heroku.com\">Add-ons</a></li>\n  <li><a href=\"https://devcenter.heroku.com\">Documentation</a></li>\n  <li><a href=\"https://help.heroku.com\">Support</a></li>\n</ul>";
      }
      return this.body.appendChild(this.div);
    };

    Hook.prototype.hideMenu = function() {
      var h;
      h = document.querySelector("#hook");
      if (h) {
        return h.classList.remove("active");
      }
    };

    Hook.prototype.toggleMenu = function(e) {
      if (e == null) {
        e = null;
      }
      document.querySelector("#hook").classList.toggle("active");
      if (e) {
        return e.stopPropagation();
      }
    };

    Hook.reset = function() {
      var h, toggler;
      h = document.getElementById('hook');
      if (h) {
        toggler = h.querySelector("a.toggler");
        if (toggler) {
          toggler.removeEventListener('click', this.toggleMenu);
        }
        window.removeEventListener('click', this.hideMenu);
        if (h) {
          return h.parentNode.removeChild(h);
        }
      }
    };

    return Hook;

  })();

  window.Hook = Hook;

}).call(this);
