// Generated by CoffeeScript 1.3.3
(function() {
  var Hook;

  Hook = (function() {

    function Hook(options) {
      this.options = options != null ? options : {};
      this.cssUrl = this.options.cssUrl || "https://s3.amazonaws.com/assets.heroku.com/hook/hook.css";
      this.corner = this.options.corner || 'tr';
      this.head = document.querySelector("head");
      this.body = document.querySelector("body");
      this.attachStylesheet();
      this.attachDiv();
      window.addEventListener('click', this.hideMenu);
      document.querySelector("#hook a.toggler").addEventListener('click', this.toggleMenu);
      console.log(this);
    }

    Hook.prototype.attachStylesheet = function() {
      var link;
      link = document.createElement("link");
      link.type = "text/css";
      link.rel = "stylesheet";
      link.href = this.cssUrl;
      return this.head.appendChild(link);
    };

    Hook.prototype.attachDiv = function() {
      this.div = document.createElement("div");
      this.div.className = "hook";
      this.div.id = "hook";
      this.div.innerHTML = "<a href=\"#\" class=\"toggler\">&#xf100</a>\n<ul>\n  <li><a href=\"https://www.heroku.com\">My Apps</a></li>\n  <li><a href=\"https://addons.heroku.com\">Addons</a></li>\n  <li><a href=\"https://devcenter.heroku.com\">Documentation</a></li>\n  <li><a href=\"https://help.heroku.com\">Support</a></li>\n</ul>";
      return this.body.appendChild(this.div);
    };

    Hook.prototype.hideMenu = function() {
      console.log('hideMenu');
      return document.querySelector("#hook").classList.remove("active");
    };

    Hook.prototype.toggleMenu = function(e) {
      document.querySelector("#hook").classList.toggle("active");
      return e.stopPropagation();
    };

    return Hook;

  })();

  window.Hook = Hook;

  document.addEventListener("DOMContentLoaded", function() {
    if (!document.querySelector("body.no-hook")) {
      return window.hook = new Hook();
    }
  });

}).call(this);
